- include_role:
    name: farynam.mfitbs_openvpn_easyrsa

- name: Create certificate for a client
  shell: easyrsa build-client-full {{ item }} nopass
  args:
    chdir: /root
    creates: "{{ PKI_DIR }}/issued/{{ item }}.crt"
  environment:
    PATH: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}:{{ ansible_env.PATH }}"
  with_items: "{{ clients }}"

- name: Grab client cert locally
  fetch:
    src: "{{PKI_DIR}}/issued/{{ item }}.crt"
    dest: "{{ local_repo }}/clients/issued/"
    flat: yes
  with_items: "{{ clients }}"

- name: Grab keys locally
  fetch:
    src: "{{PKI_DIR}}/private/{{ item }}.key"
    dest: "{{ local_repo }}/clients/private/"
    flat: yes
  with_items: "{{ clients }}"

- name: Create local clients conf directory
  local_action:
    module: file
    path: "{{ local_repo }}/clients/conf"
    state: directory
    mode: '0770'

- name: Template pc type clients
  local_action:
    module: template
    src: templates/client.conf
    dest: "{{ local_repo }}/clients/conf/{{ item }}.conf"
    mode: '0660'
    force : false
  vars:
    ca_cert: "{{ lookup('file', '{{ local_repo }}/ca.crt') }}"
    client_cert: "{{ lookup('file', '{{ local_repo }}/clients/issued/' ~ item ~ '.crt') }}"
    client_key: "{{ lookup('file',  '{{ local_repo }}/clients/private/' ~ item ~ '.key') }}"
    ta_key: "{{ lookup('file',  '{{ local_repo }}/ta.key') }}"
  with_items: "{{ clients }}"
